name: MysticAnvil
version: '1.0-c'
main: org.mysticanvil.MysticAnvil
api-version: '1.18'
author: ironPhil24k - MYSTIC SUDIO COPYRIGHT
depend:
  - Vault
commands:
  mysticanvil:
    description: Open the gui



